In [1]:
import pandas as pd
import numpy as np
import re
from collections import Counter
pd.set_option("max_columns", 100)

In [2]:
sg = pd.read_csv('../01_Raw Data/Data Files/stgames')

In [3]:
sg.head()

,appid,type,name,required_age,is_free,controller_support,dlc,pc_requirements,developers,publishers,price_overview,platforms,metacritic,categories,recommendations,achievements,release_date,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,languages,genre,ccu,tags
0,10,game,Counter-Strike,0.0,False,NaN,NaN,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,['Valve'],['Valve'],"{'currency': 'GBP', 'initial': 719, 'final': 1...","{'windows': True, 'mac': True, 'linux': True}","{'score': 88, 'url': 'https://www.metacritic.c...","[{'id': 1, 'description': 'Multi-player'}, {'i...",{'total': 90753},{'total': 0},"{'coming_soon': False, 'date': '1 Nov, 2000'}",NaN,157468,4107,0,"10,000,000 .. 20,000,000",9109,162,193,147,199.0,999.0,80.0,"English, French, German, Italian, Spanish - Sp...",Action,17438,"{'Action': 5311, 'FPS': 4713, 'Multiplayer': 3..."
1,20,game,Team Fortress Classic,0.0,False,NaN,NaN,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,['Valve'],['Valve'],"{'currency': 'GBP', 'initial': 399, 'final': 7...","{'windows': True, 'mac': True, 'linux': True}",NaN,"[{'id': 1, 'description': 'Multi-player'}, {'i...",{'total': 3445},{'total': 0},"{'coming_soon': False, 'date': '1 Apr, 1999'}",NaN,4254,776,0,"2,000,000 .. 5,000,000",100,0,12,0,99.0,499.0,80.0,"English, French, German, Italian, Spanish - Sp...",Action,136,"{'Action': 730, 'FPS': 295, 'Multiplayer': 250..."
2,30,game,Day of Defeat,0.0,False,NaN,NaN,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,['Valve'],['Valve'],"{'currency': 'GBP', 'initial': 399, 'final': 7...","{'windows': True, 'mac': True, 'linux': True}","{'score': 79, 'url': 'https://www.metacritic.c...","[{'id': 1, 'description': 'Multi-player'}, {'i...",{'total': 2598},{'total': 0},"{'coming_soon': False, 'date': '1 May, 2003'}",NaN,4264,480,0,"5,000,000 .. 10,000,000",528,1,12,2,99.0,499.0,80.0,"English, French, German, Italian, Spanish - Spain",Action,151,"{'FPS': 777, 'World War II': 242, 'Multiplayer..."
3,40,game,Deathmatch Classic,0.0,False,NaN,NaN,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,['Valve'],['Valve'],"{'currency': 'GBP', 'initial': 399, 'final': 7...","{'windows': True, 'mac': True, 'linux': True}",NaN,"[{'id': 1, 'description': 'Multi-player'}, {'i...",{'total': 1206},{'total': 0},"{'coming_soon': False, 'date': '1 Jun, 2001'}",NaN,1566,346,0,"5,000,000 .. 10,000,000",16,0,11,0,99.0,499.0,80.0,"English, French, German, Italian, Spanish - Sp...",Action,6,"{'Action': 624, 'FPS': 135, 'Classic': 103, 'M..."
4,50,game,Half-Life: Opposing Force,0.0,False,NaN,NaN,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,['Gearbox Software'],['Valve'],"{'currency': 'GBP', 'initial': 399, 'final': 7...","{'windows': True, 'mac': True, 'linux': True}",NaN,"[{'id': 2, 'description': 'Single-player'}, {'...",{'total': 6847},{'total': 0},"{'coming_soon': False, 'date': '1 Nov, 1999'}",NaN,8558,460,0,"5,000,000 .. 10,000,000",268,91,140,182,99.0,499.0,80.0,"English, French, German, Korean",Action,158,"{'FPS': 868, 'Action': 310, 'Classic': 236, 'S..."

In [4]:
sg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36726 entries, 0 to 36725
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   appid               36726 non-null  int64
 1   type                36586 non-null  object
 2   name                36723 non-null  object
 3   required_age        36586 non-null  float64
 4   is_free             36586 non-null  object
 5   controller_support  7652 non-null   object
 6   dlc                 6352 non-null   object
 7   pc_requirements     36586 non-null  object
 8   developers          36478 non-null  object
 9   publishers          36586 non-null  object
 10  price_overview      31263 non-null  object
 11  platforms           36586 non-null  object
 12  metacritic          3305 non-null   object
 13  categories          35849 non-null  object
 14  recommendations     8504 non-null   object
 15  achievements        32189 non-null  object
 16  release_date        36586 non-null  object
 17  score_rank          46 non-null     float64
 18  positive            36726 non-null  int64
 19  negative            36726 non-null  int64
 20  userscore           36726 non-null  int64
 21  owners              36726 non-null  object
 22  average_forever     36726 non-null  int64
 23  average_2weeks      36726 non-null  int64
 24  median_forever      36726 non-null  int64
 25  median_2weeks       36726 non-null  int64
 26  price               36697 non-null  float64
 27  initialprice        36704 non-null  float64
 28  discount            36704 non-null  float64
 29  languages           36628 non-null  object
 30  genre               36546 non-null  object
 31  ccu                 36726 non-null  int64
 32  tags                36726 non-null  object
dtypes: float64(5), int64(9), object(19)
memory usage: 9.2+ MB

Next, look at the columns we have and decide which to keep:
Score rank does not have enough values - drop
Recommendations - only for about 1/3 of games. Positive/Negative results probably covers this better anyway - drop
Metacritic - while this would be nice to have, having only 10% of values is not enough - drop
DLC - Not many values here. NaN values may indicate no DLC however games which are themselves DLC have a NaN value in this collumn making any analysis difficult. 
Controller Support - Mostly NaN. Many games with NaN do still support controllers so not sure how much can be gleaned from this.

In [5]:
sg.drop(["score_rank", "recommendations", "metacritic", "dlc", "controller_support"], axis=1, inplace=True)

In [6]:
sg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36726 entries, 0 to 36725
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            36726 non-null  int64
 1   type             36586 non-null  object
 2   name             36723 non-null  object
 3   required_age     36586 non-null  float64
 4   is_free          36586 non-null  object
 5   pc_requirements  36586 non-null  object
 6   developers       36478 non-null  object
 7   publishers       36586 non-null  object
 8   price_overview   31263 non-null  object
 9   platforms        36586 non-null  object
 10  categories       35849 non-null  object
 11  achievements     32189 non-null  object
 12  release_date     36586 non-null  object
 13  positive         36726 non-null  int64
 14  negative         36726 non-null  int64
 15  userscore        36726 non-null  int64
 16  owners           36726 non-null  object
 17  average_forever  36726 non-null  int64
 18  average_2weeks   36726 non-null  int64
 19  median_forever   36726 non-null  int64
 20  median_2weeks    36726 non-null  int64
 21  price            36697 non-null  float64
 22  initialprice     36704 non-null  float64
 23  discount         36704 non-null  float64
 24  languages        36628 non-null  object
 25  genre            36546 non-null  object
 26  ccu              36726 non-null  int64
 27  tags             36726 non-null  object
dtypes: float64(4), int64(9), object(15)
memory usage: 7.8+ MB

And now to look at some of the missing values for the other columns:

Type - Mostly filled with "game". Some null values. These games seem to be null in all/most columns and so they can be dropped. After that, the column will have only one value and so can be dropped too. 

Name - Two further missing vaues here. Can be removed.

In [7]:
sg.dropna(subset=["type", "name"],inplace=True)
sg.drop("type", axis=1, inplace=True)

In [8]:
sg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36584 entries, 0 to 36725
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            36584 non-null  int64
 1   name             36584 non-null  object
 2   required_age     36584 non-null  float64
 3   is_free          36584 non-null  object
 4   pc_requirements  36584 non-null  object
 5   developers       36478 non-null  object
 6   publishers       36584 non-null  object
 7   price_overview   31262 non-null  object
 8   platforms        36584 non-null  object
 9   categories       35848 non-null  object
 10  achievements     32187 non-null  object
 11  release_date     36584 non-null  object
 12  positive         36584 non-null  int64
 13  negative         36584 non-null  int64
 14  userscore        36584 non-null  int64
 15  owners           36584 non-null  object
 16  average_forever  36584 non-null  int64
 17  average_2weeks   36584 non-null  int64
 18  median_forever   36584 non-null  int64
 19  median_2weeks    36584 non-null  int64
 20  price            36583 non-null  float64
 21  initialprice     36583 non-null  float64
 22  discount         36583 non-null  float64
 23  languages        36566 non-null  object
 24  genre            36486 non-null  object
 25  ccu              36584 non-null  int64
 26  tags             36584 non-null  object
dtypes: float64(4), int64(9), object(14)
memory usage: 7.8+ MB

In [9]:
[[col, sum(sg[col].isna())] for col in sg.columns if sum(sg[col].isna())>0]

[['developers', 106],
 ['price_overview', 5322],
 ['categories', 736],
 ['achievements', 4397],
 ['price', 1],
 ['initialprice', 1],
 ['discount', 1],
 ['languages', 18],
 ['genre', 98]]

Price, initialprice and discount are all missing the same 1 value. 

Genre - 100 missing is unfortunate but genre is likely to be a big part of the analysis and so NaN values will be removed. 

Language - 18 missing. While these clearly have titles in English and so could probably be given English as a language, they are also not games that need to be included and so will be removed.

In [10]:
sg.dropna(subset=["price", "genre", "languages"],inplace=True)

In [11]:
[[col, sum(sg[col].isna())] for col in sg.columns if sum(sg[col].isna())>0]

[['developers', 63],
 ['price_overview', 5283],
 ['categories', 714],
 ['achievements', 4387]]

Developers - 63 missing values. These could be dropped but would be nice to keep these games. From a recommendation engine standpoint, this column only really needs to show games for developers with multiple games anyway. So, to tidy this up:

Where there's a list of several developers, split into individual developers. 

All NaN values can be changed to other. 

All developers with less than 5 games can be changed to other. 

Will also apply this to publishers.

In [12]:
sg["developers"] = sg["developers"].fillna("")

In [13]:
def tidycol(col,n):
    # Split up string list of developers and return only those with more than n games. Convert rest to other. 
    # Create list of individual developers for each row of table
    items = [[re.split(', ?', re.sub("'", "", i).lower()) for i in re.findall("'.+'", d)] for d in col]
    for i in range(len(items)):
        if items[i] != []:
            items[i] = [j for k in items[i] for j in k]
    # Flatten list + extract list of frequent items
    lst = dict(Counter([i for j in items for i in j]))
    lst = [key for key in lst if lst[key]>=n]
    # Return only frequent items
    outpt = [[i for i in j if i in lst] for j in items]
    for i in range(len(outpt)):
        if len(outpt[i])==0:
            outpt[i] = ["Other"]
    return outpt

In [14]:
sg["developers"] = tidycol(sg["developers"],5)
sg["publishers"] = tidycol(sg["publishers"],5)

Price overview information is better in the price, discount and initial price columns (the differece is in currency I believe). This allows me to drop the price_overview.